=head1 NAME

MooseX::Event and ONE

=head1 DESCRIPTION

MooseX::Event provides an event framework for Moose classes that is inspired
by and similar to the one included with Node.js.  It provides class helpers
to let you declare that you emit named events, methods for you to emit
events with and methods to allow users of your class to declare event
listeners.

ONE provides a layer on top of AnyEvent that uses MooseX::Event as it's
interface.  This gives you an arguably nicer, and definitely more consistant
interface to write your event based programs.

